const SAVE_KEY='cyrex_sector_one_v03';
const MAPS={sector:'https://res.cloudinary.com/dkhxur6ga/image/upload/v1778957004/53D1D4C4-9DED-4D01-AD40-9AB4754239A7_qrixbf.png',grayline:'https://res.cloudinary.com/dkhxur6ga/image/upload/v1778957004/1EFFCA3E-8042-43E2-8E20-9D8DBC996272_ijew50.png',dock12:'https://res.cloudinary.com/dkhxur6ga/image/upload/v1778957004/F6E1220F-0355-49AF-BB61-DD836B6BA2E1_s0jcif.png',blackrow:'https://res.cloudinary.com/dkhxur6ga/image/upload/v1778957005/425DA09A-B4BB-4AAB-9B3A-C1D9700A2DD4_h7un11.png',clinic:'https://res.cloudinary.com/dkhxur6ga/image/upload/v1778957004/BD6512C8-FFD5-4BAC-903F-4757B5C146A0_xwrkq2.png'};
const DATA={
professions:{scavenger:{label:'Scavenger',bonus:'Scavenge runs find extra scrap.'},courier:{label:'Courier',bonus:'Delivery jobs pay more.'},medic:{label:'Street Medic',bonus:'Clinic visits cost less.'},tech:{label:'Cybernetic Tech',bonus:'Crafting and cyber installs cost less.'},'data-runner':{label:'Data Runner',bonus:'Scans may reveal extra intel.'},'bounty-hunter':{label:'Bounty Hunter',bonus:'Combat contracts pay more.'}},
affiliations:{mp:{label:'M&P',desc:'Unaffiliated independent. Flexible, local, no banner.'},'free-cell':{label:'Free Cell',desc:'Anti-Towers. Illegal, self-owned, watched by the Grid.'},'corporate-cell':{label:'Corporate Cell',desc:'Licensed by the Towers. Funded, protected, owned.'}},
implants:{clean:'Clean Body','old-optic':'Old Optic','nerve-splint':'Nerve Splint','black-market-core':'Black-Market Core'},
districts:[{id:'grayline',title:'Grayline District',status:'Transit Lockdown',danger:'Medium',heat:4,image:MAPS.grayline,text:'Clinics, transit scaffolds, sleeping blocks, and bad light.',resources:{scrap:2,circuit:1},feed:'Grayline reports another rolling blackout.'},{id:'dock12',title:'Dock 12',status:'Industrial Port',danger:'High',heat:9,image:MAPS.dock12,text:'Cargo lanes, power cores, stolen freight, and people nobody claims.',resources:{scrap:2,power_core:1},feed:'Power cores moved through Dock 12.'},{id:'blackrow',title:'Black Market Row',status:'Undercity Access',danger:'Medium',heat:6,image:MAPS.blackrow,text:'If it can be bought, sold, installed, erased, or denied, someone here has a price.',resources:{circuit:1,data_shard:1},feed:'Black Market Row prices shifted after a Corporate Cell raid.'},{id:'clinic',title:'Clinic Quarter',status:'Medical Sector',danger:'Low',heat:2,image:MAPS.clinic,text:'Red-white light, burned nerves, clean blades, dirty credit.',resources:{med_gel:2,scrap:1},feed:'Clinic Quarter is paying above market for trauma kits.'}],
jobs:[{id:'medgel',title:'Clinic Med-Gel Delivery',type:'Delivery',difficulty:'Low',reward:90,xp:24,energy:14,heat:4,materials:{med_gel:1},text:'Move med-gel through a locked transit corridor.'},{id:'cores',title:'Recover Power Cores',type:'Recovery',difficulty:'Medium',reward:140,xp:36,energy:22,heat:10,materials:{power_core:1,scrap:2},text:'Recover charged cores near Dock 12.'},{id:'sweep',title:'Avoid Corporate Sweep',type:'Survival',difficulty:'Medium',reward:110,xp:32,energy:18,heat:-8,materials:{access_chip:1},text:'Suits are walking the lower platforms. Stay quiet.'},{id:'bounty',title:'Street Contract: Red Voss',type:'Combat',difficulty:'Hard',reward:190,xp:52,energy:30,heat:16,materials:{weapon_part:1},text:'A fixer wants Red Voss found.'},{id:'grid',title:'Grid Echo Scan',type:'Data',difficulty:'Low',reward:70,xp:22,energy:12,heat:5,materials:{data_shard:1},text:'Trace a ghost signal before the Grid closes the window.'},{id:'cell-aid',title:'Free Cell Supply Run',type:'Cell',difficulty:'Medium',reward:120,xp:34,energy:20,heat:11,materials:{access_chip:1,med_gel:1},text:'A Free Cell needs supplies moved under the Grid.'},{id:'corp-audit',title:'Corporate Compliance Audit',type:'Corporate',difficulty:'Low',reward:160,xp:26,energy:15,heat:-6,materials:{circuit:1},text:'The Towers need quiet bodies to check records.'}],
recipes:[{id:'medkit',title:'Trauma Kit',requires:{med_gel:1,scrap:1},gives:{trauma_kit:1},creditCost:10},{id:'weaponmod',title:'Crude Weapon Mod',requires:{weapon_part:1,scrap:2},gives:{weapon_mod:1},creditCost:25},{id:'corecharger',title:'Core Charger',requires:{power_core:1,circuit:2,scrap:2},gives:{core_charger:1},creditCost:40},{id:'scrambler',title:'Grid Scrambler',requires:{data_shard:1,access_chip:1,circuit:1},gives:{grid_scrambler:1},creditCost:35}],
cybernetics:[{id:'optic',title:'Old Optic Rebuild',cost:90,humanity:6,heat:3,requires:{circuit:1,data_shard:1},effect:'Scans improve.'},{id:'splint',title:'Nerve Splint Mk.I',cost:130,humanity:9,heat:5,requires:{circuit:2,scrap:2},effect:'Combat jobs pay more.'},{id:'grip',title:'Chrome Grip Tendons',cost:110,humanity:7,heat:4,requires:{scrap:3,weapon_part:1},effect:'Scavenge runs recover more scrap.'},{id:'blackcore',title:'Core Socket',cost:220,humanity:16,heat:14,requires:{power_core:1,access_chip:1},effect:'High output. Better rewards. People notice.'}],
market:[{id:'buy-scrap',title:'Buy Scrap Alloy',cost:12,gives:{scrap:1}},{id:'buy-circuit',title:'Buy Clean Circuit',cost:28,gives:{circuit:1}},{id:'buy-medgel',title:'Buy Med-Gel',cost:32,gives:{med_gel:1}},{id:'sell-scrap',title:'Sell Scrap Alloy',sell:{scrap:1},reward:7},{id:'sell-datashard',title:'Sell Data Shard',sell:{data_shard:1},reward:45}],
safehouse:[{id:'locker',title:'Wall Locker',cost:60,requires:{scrap:2},effect:'Storage secured. Reputation +5.'},{id:'workbench',title:'Scrap Workbench',cost:90,requires:{scrap:4,circuit:1},effect:'Crafting station stabilized.'},{id:'medshelf',title:'Med Shelf',cost:75,requires:{med_gel:1,scrap:1},effect:'Rest heals more health.'},{id:'jammer',title:'Signal Jammer',cost:120,requires:{circuit:2,access_chip:1},effect:'Heat reduced by 12.'}]};
let state=newState();
const el=id=>document.getElementById(id);
const createScreenEl=el('createScreen'),gameScreenEl=el('gameScreen'),startGameButtonEl=el('startGameButton'),loadGameButtonEl=el('loadGameButton'),characterNameEl=el('characterName'),professionEl=el('profession'),affiliationEl=el('affiliation'),implantEl=el('implant');
function newState(){return{name:'Jax Veyr',profession:'scavenger',affiliation:'mp',implant:'clean',credits:100,level:1,xp:0,health:100,energy:100,humanity:100,heat:6,reputation:0,activeDistrict:'grayline',hasMap:false,completedJobs:[],safehouseUpgrades:[],installedCybernetics:[],standing:{free:0,corporate:0,mp:8},inventory:{scrap:3,circuit:1,med_gel:1},feed:['Clinic requests med-gel delivery.','Power cores spotted near Dock 12.','Free Cells active under the transit spine.','Corporate Cells increased patrols in Grayline.','The Grid flagged unusual traffic.'],log:[]}}
function activeDistrict(){return DATA.districts.find(d=>d.id===state.activeDistrict)||DATA.districts[0]}
function prof(){return DATA.professions[state.profession]?.label||'Scavenger'}
function aff(){return DATA.affiliations[state.affiliation]?.label||'M&P'}
function imp(){return DATA.implants[state.implant]||'Clean Body'}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function item(k,a){state.inventory[k]=(state.inventory[k]||0)+a;if(state.inventory[k]<=0)delete state.inventory[k]}
function has(req={}){return Object.keys(req).every(k=>(state.inventory[k]||0)>=req[k])}
function spend(req={}){if(!has(req))return false;Object.keys(req).forEach(k=>item(k,-req[k]));return true}
function fmt(k){return k.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function req(items={}){return Object.entries(items).map(([k,v])=>`${fmt(k)} x${v}`).join(', ')}
function log(m){state.log.push(m);if(state.log.length>80)state.log.shift();renderLog()}
function feed(m){state.feed.unshift(m);if(state.feed.length>12)state.feed.pop()}
function xp(a){state.xp+=a;let need=state.level*100;if(state.xp>=need){state.xp-=need;state.level++;state.health=clamp(state.health+15,0,100);state.energy=clamp(state.energy+15,0,100);log('<strong>LEVEL UP:</strong> Level '+state.level+'.')}}
function startGame(){state=newState();state.name=characterNameEl.value.trim()||'Unnamed Citizen';state.profession=professionEl.value;state.affiliation=affiliationEl.value;state.implant=implantEl.value;if(state.affiliation==='free-cell'){state.heat+=10;state.reputation+=10;state.standing.free+=20;feed('A Free Cell contact marks your name as useful.')}if(state.affiliation==='corporate-cell'){state.credits+=80;state.heat=clamp(state.heat-2,0,100);state.reputation+=4;state.standing.corporate+=22;feed('Corporate Cell registry approved. The Ledger has your signature.')}if(state.affiliation==='mp'){state.credits+=25;state.reputation+=6;state.standing.mp+=18;feed('M&P operators keep moving without a banner.')}if(state.implant==='old-optic'){state.humanity-=6;state.hasMap=true;state.installedCybernetics.push('optic')}if(state.implant==='nerve-splint'){state.humanity-=10;state.installedCybernetics.push('splint')}if(state.implant==='black-market-core'){state.credits+=90;state.humanity-=20;state.heat+=12;item('power_core',1);state.installedCybernetics.push('blackcore')}createScreenEl.style.display='none';gameScreenEl.style.display='grid';state.log=[];log('<strong>SYSTEM:</strong> Neural link unstable.');log('<strong>PROFILE:</strong> '+state.name+'. '+prof()+'. '+aff()+'. '+imp()+'.');log('<strong>MESSAGE:</strong> Sector One opens.');save(false);renderAll()}
function renderAll(){el('playerName').textContent=state.name;el('professionText').textContent=prof();el('affiliationText').textContent=aff();el('credits').textContent=state.credits;el('levelText').textContent=state.level;renderDistrictHero();renderMeters();renderFeed();renderDistricts();renderJobs();renderInventory();renderCrafting();renderMarket();renderSafehouse();renderCybernetics();renderCells();renderProfile();renderLog()}
function renderDistrictHero(){let d=activeDistrict(),card=el('districtHeroCard');if(card)card.style.backgroundImage=`linear-gradient(to bottom,rgba(0,0,0,.08),rgba(0,0,0,.24)),url('${d.image}')`;el('sceneTitle').textContent=d.title;el('sceneDesc').textContent=`${d.status}. Danger ${d.danger}. ${d.text}`;el('districtName').textContent=d.title;el('districtCopy').textContent=d.text}
function renderMeters(){[['health',state.health],['energy',state.energy],['humanity',state.humanity],['heat',state.heat]].forEach(([k,v])=>{el(k+'Text').textContent=v+'%';el(k+'Meter').value=v})}
function renderFeed(){el('cityFeed').innerHTML=state.feed.map((x,i)=>`<div class="cyrex-feed-item"><span>${i===0?'LIVE':'FEED'}</span><p>${x}</p></div>`).join('')}
function renderDistricts(){el('districtList').innerHTML=`<article class="cyrex-map-preview"><img src="${MAPS.sector}" alt="Sector One Overview"><div><strong>Sector One Overview</strong><span>Full sector map</span></div></article>`+DATA.districts.map(d=>`<article class="cyrex-list-card ${d.id===state.activeDistrict?'selected':''}"><img class="cyrex-card-map" src="${d.image}" alt="${d.title} map"><div><strong>${d.title}</strong><span>${d.status}</span></div><p>${d.text}</p><small>Danger: ${d.danger} · Heat +${d.heat}</small><button data-district="${d.id}">${d.id===state.activeDistrict?'Active':'Travel'}</button></article>`).join('')}
function renderJobs(){el('jobsList').innerHTML=DATA.jobs.map(j=>{let done=state.completedJobs.includes(j.id);return`<article class="cyrex-list-card"><div><strong>${j.title}</strong><span>${j.type} · ${j.difficulty}</span></div><p>${j.text}</p><small>${j.reward} cr · ${j.xp} XP · Energy ${j.energy}</small><button data-job="${j.id}" ${done?'disabled':''}>${done?'Completed':'Take Job'}</button></article>`}).join('')}
function renderInventory(){let e=Object.entries(state.inventory);el('inventoryList').innerHTML=e.length?e.map(([k,v])=>`<article class="cyrex-list-card compact"><strong>${fmt(k)}</strong><span>x${v}</span></article>`).join(''):`<article class="cyrex-list-card"><p>No gear. No parts.</p></article>`}
function renderCrafting(){el('craftingList').innerHTML=DATA.recipes.map(r=>`<article class="cyrex-list-card"><div><strong>${r.title}</strong><span>${r.creditCost} cr</span></div><p>Requires: ${req(r.requires)}</p><small>Creates: ${req(r.gives)}</small><button data-craft="${r.id}" ${state.credits>=r.creditCost&&has(r.requires)?'':'disabled'}>Craft</button></article>`).join('')}
function renderMarket(){el('marketList').innerHTML=DATA.market.map(m=>`<article class="cyrex-list-card"><div><strong>${m.title}</strong><span>${m.cost?m.cost+' cr':'+'+m.reward+' cr'}</span></div><button data-market="${m.id}">${m.cost?'Buy':'Sell'}</button></article>`).join('')}
function renderSafehouse(){el('safehouseList').innerHTML=DATA.safehouse.map(u=>{let owned=state.safehouseUpgrades.includes(u.id),can=!owned&&state.credits>=u.cost&&has(u.requires);return`<article class="cyrex-list-card"><div><strong>${u.title}</strong><span>${owned?'Installed':u.cost+' cr'}</span></div><p>${u.effect}</p><small>Requires: ${req(u.requires)}</small><button data-upgrade="${u.id}" ${can?'':'disabled'}>${owned?'Installed':'Install'}</button></article>`}).join('')}
function renderCybernetics(){el('cyberneticsList').innerHTML=DATA.cybernetics.map(c=>{let installed=state.installedCybernetics.includes(c.id),cost=state.profession==='tech'?Math.max(20,c.cost-25):c.cost,can=!installed&&state.credits>=cost&&has(c.requires)&&state.humanity>c.humanity;return`<article class="cyrex-list-card ${installed?'selected':''}"><div><strong>${c.title}</strong><span>${installed?'Installed':cost+' cr'}</span></div><p>${c.effect}</p><small>Humanity -${c.humanity} · Heat +${c.heat} · Requires: ${req(c.requires)}</small><button data-cyber="${c.id}" ${can?'':'disabled'}>${installed?'Installed':'Install'}</button></article>`}).join('')}
function renderCells(){let a=DATA.affiliations[state.affiliation];el('cellsPanel').innerHTML=`<article class="cyrex-list-card"><div><strong>Current Standing</strong><span>${aff()}</span></div><p>${a.desc}</p></article><article class="cyrex-list-card compact"><strong>Free Cell Standing</strong><span>${state.standing.free}</span></article><article class="cyrex-list-card compact"><strong>Corporate Cell Standing</strong><span>${state.standing.corporate}</span></article><article class="cyrex-list-card compact"><strong>M&P Standing</strong><span>${state.standing.mp}</span></article><article class="cyrex-list-card"><div><strong>Cell Base</strong><span>Locked</span></div><p>Communal cell bases come later.</p></article>`}
function renderProfile(){let p=[['Name',state.name],['Profession',prof()],['Affiliation',aff()],['Implant',imp()],['Level',state.level],['XP',state.xp+' / '+state.level*100],['Credits',state.credits],['Reputation',state.reputation],['District',activeDistrict().title],['Cybernetics',state.installedCybernetics.length],['Profession Bonus',DATA.professions[state.profession].bonus],['Affiliation Note',DATA.affiliations[state.affiliation].desc]];el('profilePanel').innerHTML=p.map(([l,v])=>`<div><span>${l}</span><strong>${v}</strong></div>`).join('')}
function renderLog(){let out=el('log');if(!out)return;out.innerHTML=state.log.map(m=>`<p>${m}</p>`).join('');out.scrollTop=out.scrollHeight}
function runJob(id){let j=DATA.jobs.find(x=>x.id===id);if(!j||state.completedJobs.includes(j.id))return;if(state.energy<j.energy)return log('<span class="warning">Not enough energy.</span>');state.energy=clamp(state.energy-j.energy,0,100);let reward=j.reward;if(state.profession==='courier'&&j.type==='Delivery')reward+=15;if(state.profession==='bounty-hunter'&&j.type==='Combat')reward+=20;if(state.installedCybernetics.includes('splint')&&j.type==='Combat')reward+=15;if(state.installedCybernetics.includes('blackcore'))reward+=12;state.credits+=reward;state.heat=clamp(state.heat+j.heat,0,100);state.reputation+=Math.round(j.xp/4);if(j.type==='Cell')state.standing.free+=6;if(j.type==='Corporate')state.standing.corporate+=6;if(['Delivery','Recovery'].includes(j.type))state.standing.mp+=2;xp(j.xp);Object.entries(j.materials).forEach(([k,v])=>item(k,v));if(state.profession==='scavenger'&&['Recovery','Survival'].includes(j.type))item('scrap',1);if(state.profession==='data-runner'&&j.type==='Data')item('circuit',1);state.completedJobs.push(j.id);feed(`${j.title} completed by ${state.name}.`);log(`<strong>JOB COMPLETE:</strong> ${j.title}. Paid ${reward} credits.`);save(false);renderAll()}
function craftItem(id){let r=DATA.recipes.find(x=>x.id===id);if(!r)return;if(state.credits<r.creditCost||!spend(r.requires)){log('<span class="warning">Missing credits or materials.</span>');renderAll();return}state.credits-=r.creditCost;Object.entries(r.gives).forEach(([k,v])=>item(k,v));if(state.profession==='tech'&&Math.random()>.5)item('scrap',1);log(`<strong>CRAFTED:</strong> ${r.title}.`);save(false);renderAll()}
function useMarket(id){let m=DATA.market.find(x=>x.id===id);if(!m)return;if(m.cost){if(state.credits<m.cost)return log('<span class="warning">Not enough credits.</span>');state.credits-=m.cost;Object.entries(m.gives).forEach(([k,v])=>item(k,v));log(`<strong>MARKET:</strong> ${m.title}.`)}else if(m.sell){if(!spend(m.sell)){log('<span class="warning">You do not have the item.</span>');renderAll();return}state.credits+=m.reward;log(`<strong>MARKET:</strong> Sale completed for ${m.reward} credits.`)}save(false);renderAll()}
function installUpgrade(id){let u=DATA.safehouse.find(x=>x.id===id);if(!u||state.safehouseUpgrades.includes(u.id))return;if(state.credits<u.cost||!spend(u.requires)){log('<span class="warning">Missing credits or materials.</span>');renderAll();return}state.credits-=u.cost;state.safehouseUpgrades.push(u.id);if(u.id==='locker')state.reputation+=5;if(u.id==='jammer')state.heat=clamp(state.heat-12,0,100);log(`<strong>SAFEHOUSE:</strong> ${u.title} installed.`);save(false);renderAll()}
function installCyber(id){let c=DATA.cybernetics.find(x=>x.id===id);if(!c||state.installedCybernetics.includes(c.id))return;let cost=state.profession==='tech'?Math.max(20,c.cost-25):c.cost;if(state.credits<cost||!spend(c.requires)||state.humanity<=c.humanity){log('<span class="warning">Install denied.</span>');renderAll();return}state.credits-=cost;state.humanity=clamp(state.humanity-c.humanity,0,100);state.heat=clamp(state.heat+c.heat,0,100);state.installedCybernetics.push(c.id);log(`<strong>CYBERNETIC INSTALLED:</strong> ${c.title}. Humanity reduced.`);feed(`${state.name} registered new chrome activity in ${activeDistrict().title}.`);save(false);renderAll()}
function travelDistrict(id){let d=DATA.districts.find(x=>x.id===id);if(!d)return;state.activeDistrict=d.id;state.energy=clamp(state.energy-6,0,100);state.heat=clamp(state.heat+d.heat,0,100);feed(d.feed);log(`<strong>TRAVEL:</strong> Entered ${d.title}.`);save(false);renderAll()}
function handleAction(a){if(a==='enter-district'){switchPanel('district');log('<strong>DISTRICT:</strong> '+activeDistrict().title+' opens under bad light.')}if(a==='refresh-feed'){let v=['The Towers deny reports of forced relocations.','M&P vendors raised prices after the lockdown.','A Corporate Cell convoy moved through Sector Nine.','Free Cell graffiti appeared on a Grid checkpoint.','A clinic is buying trauma kits above market.'];feed(v[Math.floor(Math.random()*v.length)]);log('<strong>FEED:</strong> City feed refreshed.')}if(a==='scavenge-run'){if(state.energy<10)return log('<span class="warning">Not enough energy.</span>');let d=activeDistrict();state.energy-=10;Object.entries(d.resources).forEach(([k,v])=>item(k,v));if(state.profession==='scavenger'||state.installedCybernetics.includes('grip'))item('scrap',1);state.heat=clamp(state.heat+3,0,100);xp(12);log('<strong>SCAVENGE:</strong> Materials recovered from '+d.title+'.')}if(a==='scan-district'){if(state.profession==='data-runner'||state.installedCybernetics.includes('optic'))item('data_shard',1);state.hasMap=true;log('<strong>SCAN:</strong> District map updated.')}if(a==='visit-clinic'){let cost=state.profession==='medic'?18:30;if(state.credits<cost)return log('<span class="warning">Clinic refused treatment.</span>');state.credits-=cost;state.health=clamp(state.health+35,0,100);log(`<strong>CLINIC:</strong> Wounds patched. ${cost} credits gone.`)}if(a==='rest-cycle'){state.energy=clamp(state.energy+30,0,100);state.health=clamp(state.health+(state.safehouseUpgrades.includes('medshelf')?20:10),0,100);log('<strong>REST:</strong> You sleep in fragments.')}if(a==='save-game')save(true);if(a==='reset-game')resetGame();renderAll()}
function switchPanel(panel){document.querySelectorAll('.cyrex-panel').forEach(x=>x.classList.toggle('is-active',x.dataset.panel===panel));document.querySelectorAll('.cyrex-tabs button').forEach(x=>x.classList.toggle('is-active',x.dataset.tab===panel))}
function save(show=true){localStorage.setItem(SAVE_KEY,JSON.stringify(state));if(show)log('<strong>SAVE:</strong> Local progress saved.')}
function loadLocal(){let raw=localStorage.getItem(SAVE_KEY)||localStorage.getItem('cyrex_sector_one_v02');if(!raw){alert('No local Cyrex save found yet.');return}state={...newState(),...JSON.parse(raw)};state.standing={...newState().standing,...(state.standing||{})};state.installedCybernetics=state.installedCybernetics||[];state.activeDistrict=state.activeDistrict||'grayline';createScreenEl.style.display='none';gameScreenEl.style.display='grid';log('<strong>LOAD:</strong> Local save restored.');renderAll()}
function resetGame(){localStorage.removeItem(SAVE_KEY);localStorage.removeItem('cyrex_sector_one_v02');window.location.reload()}
startGameButtonEl.addEventListener('click',startGame);loadGameButtonEl.addEventListener('click',loadLocal);
document.addEventListener('click',e=>{let tab=e.target.closest('[data-tab]');if(tab)switchPanel(tab.dataset.tab);let action=e.target.closest('[data-action]');if(action)handleAction(action.dataset.action);let district=e.target.closest('[data-district]');if(district)travelDistrict(district.dataset.district);let job=e.target.closest('[data-job]');if(job)runJob(job.dataset.job);let craft=e.target.closest('[data-craft]');if(craft)craftItem(craft.dataset.craft);let market=e.target.closest('[data-market]');if(market)useMarket(market.dataset.market);let upgrade=e.target.closest('[data-upgrade]');if(upgrade)installUpgrade(upgrade.dataset.upgrade);let cyber=e.target.closest('[data-cyber]');if(cyber)installCyber(cyber.dataset.cyber)});
